import Foundation

/// The device-side registration record synchronised with the backend.
///
/// The identifier is generated by the SDK and is deliberately independent of the push token and
/// of the user: a token refresh or a logout must never change it.
public struct Installation: Equatable {
    public let id: String
    public let applicationId: String?
    public let platform: String
    public let provider: PushProvider
    public let pushToken: String?
    public let userId: String?
    public let appVersion: String?
    public let appBuild: String?
    public let sdkVersion: String
    public let osVersion: String?
    public let deviceModel: String?
    public let locale: String?
    public let timezone: String?
    public let notificationsEnabled: Bool

    public init(
        id: String,
        applicationId: String?,
        platform: String,
        provider: PushProvider,
        pushToken: String?,
        userId: String?,
        appVersion: String?,
        appBuild: String?,
        sdkVersion: String,
        osVersion: String?,
        deviceModel: String?,
        locale: String?,
        timezone: String?,
        notificationsEnabled: Bool
    ) {
        self.id = id
        self.applicationId = applicationId
        self.platform = platform
        self.provider = provider
        self.pushToken = pushToken
        self.userId = userId
        self.appVersion = appVersion
        self.appBuild = appBuild
        self.sdkVersion = sdkVersion
        self.osVersion = osVersion
        self.deviceModel = deviceModel
        self.locale = locale
        self.timezone = timezone
        self.notificationsEnabled = notificationsEnabled
    }
}

/// A push-related analytics event.
///
/// The SDK is not a general analytics product. Events exist so notification delivery and
/// engagement can be attributed on the push backend; keep them focused on push.
public struct PushEvent: Equatable {
    public let name: String
    public let properties: [String: String]
    public let occurredAt: Date

    public init(name: String, properties: [String: String] = [:], occurredAt: Date = Date()) {
        self.name = name
        self.properties = properties
        self.occurredAt = occurredAt
    }
}
