package com.ary.push.model

/**
 * The device-side registration record synchronised with the backend.
 *
 * The [id] is generated by the SDK and is deliberately independent of the push token and of the
 * user: a token refresh or a logout must never change it.
 */
public data class Installation(
    /** SDK-generated, persistent, per-application installation identifier. */
    public val id: String,

    /** Optional public application identifier, e.g. `wallet_android`. Never a secret. */
    public val applicationId: String?,

    /** Always `"android"` for this SDK. */
    public val platform: String,

    /** Transport that issued [pushToken]. */
    public val provider: PushProvider,

    /** Current push token, or null before the first token has been issued. */
    public val pushToken: String?,

    /** Associated user identifier, or null when logged out. */
    public val userId: String?,

    /** Host application version name. */
    public val appVersion: String?,

    /** Host application version code. */
    public val appBuild: String?,

    /** ARY Push SDK version. */
    public val sdkVersion: String,

    /** Operating system version, e.g. `14`. */
    public val osVersion: String?,

    /** Device model, e.g. `Pixel 8`. */
    public val deviceModel: String?,

    /** BCP-47 locale, e.g. `en-PK`. */
    public val locale: String?,

    /** IANA timezone, e.g. `Asia/Karachi`. */
    public val timezone: String?,

    /** Whether notifications are currently permitted. */
    public val notificationsEnabled: Boolean
)
